# Add-on
id=theme_trans
name="Theme Trans"
author=Kakathic
description="Translate theme, widget, aod"
version=1.0
versionCode=100
root=true

# default
google_text="Currently using a translation tool"
widget_text_1="Auto-translate"
widget_text_2="Selection"
widget_text_3="Customizable widgets"
widget_text_4="Decode"
widget_text_5="Build"
widget_text_6="No widgets available"
widget_text_7="Please download some widgets, add them to your home screen, and refresh the page to display the list."
widget_text_8="Widget List"
widget_text_9="GIF image"
widget_text_10="Mark for deletion"
widget_text_11="Deleted"
widget_text_12="It will restore the untranslated version when you visit the widget store in this widget section"
widget_text_13="Hidden"
widget_text_14="Hide Widget"
widget_text_15="After translation, you can hide the widget to load other widget lists faster"
widget_text_16="Translated Widget"
widget_text_17="A Gemini API key is required beforehand"
widget_lang_1="Applied"
widget_lang_2="Saved in"
widget_lang_3="Extraction folder not found."
widget_lang_4="Error: Extracting widget"
widget_lang_5="Unable to connect to the server, please try again!"
widget_lang_6="An internet connection is required to use!"
widget_lang_7="Free trial exhausted, please support to continue"
widget_lang_8="Only accept transactions via"
widget_lang_9="device"
widget_lang_10="When sending, include the activation code, or send a screenshot with the activation code via"
widget_lang_11="Activation code"
widget_lang_12="Checking API key"
note_genmini_text="Click the 3-dot menu in the top right corner to create a free API key."
api_key_text="API Key"
generate_text="Generating Gemini API keys"
widget_lang_13="is valid and active"
widget_lang_14="is faulty or expired! (HTTP error code"
check_key_text="Activation check"
widget_lang_15="The device has been activated"
widget_lang_16="The device is not yet activated. Please support to activate it"

# other languages
case "$LANGUAGE-$COUNTRY" in
  vi*)
name="Việt hóa widget"
description="Dịch chủ đề, widget, aod"
widget_text_1="Dịch tự động"
widget_text_2="Lựa chọn"
widget_text_3="Có thể tùy chỉnh widget"
widget_text_4="Giải mã"
widget_text_5="Xây dựng"
widget_text_6="Không có widget nào"
widget_text_7="Hãy tải một vài widget và lôi ra ngoài màn hình chính và làm mới trang để xuất hiện danh sách."
widget_text_8="Danh sách Widget"
widget_text_9="Ảnh GIF"
widget_text_10="Đánh dấu xoá bỏ"
widget_text_11="Đã xoá"
widget_text_12="Nó sẽ khôi phục lại phiên bản chưa dịch khi bạn vào cửa hàng widget ở chỗ mục widget này"
widget_text_13="Đã được ẩn"
widget_text_14="Ẩn Widget"
widget_text_15="Sau khi dịch xong có thể ẩn widget để load danh sách widget khác nhanh hơn"
widget_text_16="Widget đã dịch"
widget_text_17="Yêu cầu có khóa API Gemini trước"
widget_lang_1="Đã được áp dụng"
widget_lang_2="Lưu ở"
widget_lang_3="Không tìm thấy thư mục giải nén."
widget_lang_4="Lỗi: Giải nén widget"
widget_lang_5="Không thể kết nối với máy chủ, Hãy thử lại!"
widget_lang_6="Cần kết nối mạng để sử dụng !"
widget_lang_7="Số lần dùng thử đã hết, để tiếp tục hãy ủng hộ"
widget_lang_8="Chỉ chấp nhận giao dịch qua"
widget_lang_9="thiết bị"
widget_lang_10="Khi gửi, kèm mã kích hoạt, hoặc gửi ảnh chụp màn hình kèm mã kích hoạt qua"
widget_lang_11="Mã kích hoạt"
widget_lang_12="Đang kiểm tra API"
api_key_text="Mã khóa API"
note_genmini_text="Nhấn menu 3 chấm ở góc phải để tạo khoá API miễn phí"
generate_text="Tạo khoá API Gemini"
widget_lang_13="là hợp lệ và đang hoạt động"
widget_lang_14="bị lỗi hoặc hết hạn! (Mã lỗi HTTP"
check_key_text="Kiểm tra kích hoạt"
widget_lang_15="Thiết bị đã được kích hoạt"
widget_lang_16="Thiết bị chưa được kích hoạt, Ủng hộ để kích hoạt"
    ;;
  *)
    ;;
esac
