NOT_FOUND_TEXT="Không tìm thấy" # Not found
SUMMARY_CURRENT="Hiện hành" # Current
patch_text1="Vá" # Patching
LABEL_FIX_THEME="Khắc phục sự cố đặt lại chủ đề" # Fix theme reset issue
TITLE_FAST_PATCH="Bản vá nhanh cơ bản" # Basic fast patch
patch_text="Đã vá" # Patched
LABEL_DELETE_APP="Xóa bloatware" # Remove bloatware
LABEL_DISABLE_OTA="Tắt cập nhật OTA" # Disable OTA update
LABEL_SELECT="Lựa chọn" # Select
LABEL_FIX_APPVAULT="Mở khóa các giao dịch Appvault" # Unlock Appvault transactions
DESC_COLOR_DARK="Mã màu nền tối" # Dark background color code
LABEL_CRYPTO="Thêm ro.crypto.state=encrypted" # Add ro.crypto.state=encrypted
LABEL_FIX_SCREEN="Mở khóa hạn chế ảnh chụp màn hình" # Unlock screenshot restriction
google_text="Hiện đang sử dụng google dịch" # Currently using google translate
LABEL_FIX_ERROR="Xóa hộp thoại báo lỗi vân tay khi khởi động" # Remove fingerprint error dialog at boot
LABEL_FIX_NOTI="Sửa lỗi thông báo bị trì hoãn (CN)" # Fix delayed notification (CN)
LABEL_FIX_FPS="Mở khóa FPS tối đa" # Unlock max FPS
LABEL_FIX_THEMES="Mở khóa các giao dịch Theme" # Unlock Theme transactions
SEARCHING_AND_DELETING="Tìm kiếm và xóa..." # Searching and deleting...
LABEL_FIX_GLOBAL="Kích hoạt tính năng ROM toàn cầu trên CN ROM" # Enable global ROM features on CN ROM
LABEL_OAT_FW="Tạo yến mạch cho framework và dịch vụ" # Create oat for framework and services
LABEL_FIX_FWKO="Thêm hộp công cụ Kaorios" # Add Kaorios Toolbox
LABEL_FIX_IME="Bàn phím nâng cao" # Enhanced keyboard
TITLE_KEYBOARD="Tùy chỉnh bàn phím" # Keyboard customization
LABEL_FIX_APKSIGN="Bỏ qua xác minh chữ ký" # Bypass signature verification
TITLE_DEX2OAT="Dex2oat tất cả" # Dex2oat all
CREATING_OAT_TEXT="Tạo yến mạch" # Creating oat
LABEL_FIX_WINDOW="Lên đến 6 cửa sổ nổi" # Up to 6 floating windows
TITLE_REMOVE_APP="Xóa bloatware" # Remove bloatware
DESC_IME_APP="Ứng dụng bàn phím" # Keyboard application
LABEL_FIX_JOYOSE="Ứng dụng Mod Joyose" # Mod Joyose application
RW_ROM_TEXT_1="Cảnh báo: không tìm thấy nhà cung cấp_boot. Nếu nó đã được vá cho RW thì có thể bỏ qua điều này!" # Warning: vendor_boot not found. If it has already been patched for RW, this can be ignored!
DESC_HOME_POCO="Lưu ý: Chỉ thay đổi com.mi.android.globallauncher thành com.miui.home trong prop. APK phải được sửa đổi thủ công." # Note: Only changes com.mi.android.globallauncher to com.miui.home in prop. APK must be modified manually.
DESC_COLOR_LIGHT="Mã màu nền sáng" # Light background color code
TITLE_PROP="Thay đổi ro.control_privapp_permissions" # Change ro.control_privapp_permissions
RW_ROM_TEXT_3="Cảnh báo: không tìm thấy phân vùng ext4. Nó phải được thêm thủ công vào:" # Warning: ext4 partition not found. It must be added manually to:
LABEL_FIX_MAP="Xóa bản đồ Trung Quốc khỏi thư viện CN" # Remove China map from CN libraries
RW_ROM_TEXT_2="Cảnh báo: không tìm thấy mi_ext. Không thể sao chép tập tin và một số tính năng có thể bị lỗi. Nếu đã được sao chép, điều này có thể được bỏ qua!" # Warning: mi_ext not found. Files cannot be copied and some features may fail. If already copied, this can be ignored!
DESC_SECONTEXT="Nhập đường dẫn lớp cho ứng dụng. Một số ứng dụng yêu cầu đường dẫn lớp; bạn có thể kiểm tra tệp odex cũ để xem đường dẫn lớp." # Enter the class path for the application. Some apps require a class path; you can check the old odex file to see the class path.
NOTE_PATCH="Lưu ý: Sau khi áp dụng, các tính năng đã bật sẽ được áp dụng vĩnh viễn cho dự án và không thể tắt được. Bạn phải giải mã lại toàn bộ phân vùng nếu muốn thay đổi các tính năng khác." # Note: After applying, enabled features will be permanently applied to the project and cannot be disabled. You must decrypt the entire partition again if you want to change other features.
LABEL_HOME_POCO="Thay đổi POCO TRANG CHỦ" # Change POCO HOME
NO_VALUE_TEXT="Không có giá trị!" # No value!
DESC_DIMEN="Điều chỉnh kích thước chiều rộng" # Adjust width dimen
LABEL_RW_ROM="Patch RW ROM (erofs)" # Patch RW ROM (erofs)
TITLE_SYSTEM_PATCH="Bản vá hệ thống" # System patch
TITLE_CHANGE_PROJECT="Thay đổi dự án" # Change project
DESC_PROP="Thực thi: thiếu quyền có thể gây ra bootloop, log: ghi lỗi vào logcat và không cấp quyền, vô hiệu hóa: tự động cấp quyền bị thiếu cho ứng dụng" # enforce: missing permissions may cause bootloop, log: log the error to logcat and do not grant the permission, disable: automatically grant missing permissions to the app
LABEL_FIX_WEATHER="Hiển thị AQI trong thời tiết CN" # Show AQI in CN weather
