# Kakathic

if [ "$LANGUAGE-$COUNTRY" == "vi-VN" ];then
project_text="Dự án"
string_text_1="Tệp đầu vào ở dự án"
select_text="Lựa chọn"
network_text="Vui lòng kết nối mạng !"
addon_noti="Có phiên bản mới, ấn nút 3 chấm để cập nhật add-on"
desc_ime_app="Ứng dụng bàn phím"
desc_color_light="Mã màu nền sáng"
desc_color_dark="Mã màu nền tối"
desc_dimen="Điều chỉnh dimen chiều rộng"
required_files_text="Tệp cần thiết"
title_quick="Tùy chỉnh trực tiếp"
desc_patch_prop="Sửa lại ro.control_privapp_permissions"
desc_patch_prop_long="enforce: nếu thiếu quyền có thể bị bootloop, log: ghi lỗi vào log không tự sửa lỗi, disable: tự sửa lỗi nếu thiếu quyền"
label_device_features="Tắt cập nhật ota Xiaomi"
label_rw_rom="Sửa lại fstab để hỗ trợ RW-ROM"
desc_rw_rom="Xoá những dòng overlay trong fstab, cần build sang ext4 để hoàn thành RW"
label_delete_gms="Xoá gms CN update Xiaomi"
desc_delete_gms="Xoá tệp cn.google.services.xml"
label_home_poco="Thay đổi tên gói Launch POCO"
desc_home_poco="Lưu ý chỉ thay đổi: com.mi.android.globallauncher thành com.miui.home ở prop, apk cần thay đổi thủ công"
title_delete="Xoá app, tệp hàng loạt"
title_framework_patch="Bản vá framework"
label_fix_toolbox="Bản vá Kaorios Toolbox"
label_fix_apksign="Bỏ qua xác minh chữ ký"
title_cn_global="Bản vá CN ➠ Global"
label_fix_noti="Sửa thông báo chậm"
label_fix_global="Mod một số tính năng global"
title_ime="Mở khóa bàn phím nâng cao"
title_many_patch="Nhiều bản vá khác"
label_fix_screen="Mở khóa giới hạn chụp ảnh màn hình"
label_fix_fps="Mở khóa giới hạn fps"
label_fix_window="Mở khóa giới hạn cửa sổ nhỏ"
label_fix_reset_theme="Sửa lỗi khôi phục lại Chủ đề"
label_fix_show_error="Fix hộp thoại lỗi ở màn hình khóa"
title_app_patch="Bản vá các ứng dụng"
label_fix_themes="Mở khóa mua hàng Chủ đề"
label_fix_appvault="Mở khóa mua hàng App vault"
label_fix_thoit="Mod hiện Aqi Weather CN"
label_fix_joyose="Mod Joyose"
label_fix_mapcn="Mod ẩn Map CN Thư viện"
fi
