
if [ "$LANGUAGE-$COUNTRY" == "vi-VN" ]; then
home_text_1="Tạo overlay"
home_text_2="Tạo một overlay từ thư mục ngôn ngữ"
home_text_3="Trích xuất ngôn ngữ"
home_text_4="Trích xuất các ngôn ngữ từ tệp tin APK để tạo một overlay"
home_text_5="Ngôn ngữ"
home_text_6="Chỉ trích xuất các ngôn ngữ đã có sẵn, nếu bỏ trống sẽ lấy tất cả các ngôn ngữ: values-vi,values-zh-rCN"
home_text_7="Thư mục phải chứa cấu trúc thư mục ngôn ngữ, ví dụ: App/res/values-vi/strings.xml"
home_text_8="Thư mục phải chứa một tệp tin APK"

overlay_text_1="Không tìm thấy thư mục"
overlay_text_2="Đã tạo danh sách overlay. Vui lòng thêm package vào danh sách:"
overlay_text_3="Thư mục trống"
overlay_text_4="Bắt đầu tạo overlay..."
overlay_text_5="Đang tạo"
overlay_text_6="Đã tồn tại"
overlay_text_7="Đã bỏ qua"
overlay_text_8="Lỗi xây dựng overlay, kiểm tra log:"
overlay_text_9="Lưu tại:"
overlay_text_10="Lỗi giải mã (decode) APK, xem log:"
overlay_text_11="Đang nhập framework..."
elif [ "$LANGUAGE-$COUNTRY" == "hu-HU" ]; then
home_text_1="Hozz létre egy átfedést (overlay)"
home_text_2="H hozzon létre overlay-t a nyelvi könyvtárból"
home_text_3="Nyelvkinyerés"
home_text_4="Nyelvi fájlok kinyerése APK-fájlból overlay létrehozásához"
home_text_5="Nyelv"
home_text_6="Csak a megadott nyelveket bontsa ki; ha üresen hagyja, az összes nyelv benne lesz: values-vi, values-zh-rCN"
home_text_7="A könyvtárnak tartalmaznia kell egy nyelvi könyvtárstruktúrát, például: App/res/values-hu/strings.xml"
home_text_8="A könyvtárnak tartalmaznia kell egy APK-fájlt"

overlay_text_1="A könyvtár nem található"
overlay_text_2="Overlay-lista létrehozva. Kérjük, adja hozzá a csomagot a listához:"
overlay_text_3="Üres mappa"
overlay_text_4="Átfedés létrehozása folyamatban..."
overlay_text_5="Létrehozás"
overlay_text_6="Már létezik"
overlay_text_7="Kihagyva"
overlay_text_8="Hiba az overlay összeállítása során, ellenőrizze a naplót:"
overlay_text_9="Mentve ide:"
overlay_text_10="APK-dekódolási hiba, ellenőrizze a naplót:"
overlay_text_11="framework betöltése..."
fi
