
if [ "$LANGUAGE-$COUNTRY" == "vi-VN" ]; then
config_text_1="Danh sách các dự án hiện có"
setting_text_3="Dự án"
input_text="Nhập tệp tin"
folder_text="Thư mục chứa:"
error_text="Tệp tin lỗi:"
select_text="Tùy chọn"
save_text="Lưu tại"
mi_thermal_text="Giải mã - Mã hóa mi_thermald"
protoc_text="Giải mã - Mã hóa tệp tin cấu trúc .pb"
name_text="Tên"
sign_text="Chữ ký"
project_text="Dự án"
oat_text_1="Lưu ý: Chỉ hỗ trợ tạo dex2oat cho cùng loại ROM và cùng phiên bản Android. Các phân vùng cần thiết: system, system_ext"
oat_text_2="Dự án hiện tại:"
oat_text_3="Dex2oat"
oat_text_4="Xây dựng lại odex, vdex, oat, art trong framework"
oat_text_5="Xây dựng lại framework oat"
oat_text_6="Xây dựng lại services oat"
oat_text_7="Tính năng"
oat_text_8="Ứng dụng"
oat_text_9="Nhập classpath cho ứng dụng. Một số ứng dụng yêu cầu classpath; bạn có thể kiểm tra tệp tin odex cũ để xem classpath"
splitapp_desc_text="Trích xuất hình ảnh từ UPDATE.APP"
pac_desc_text="Trích xuất tệp tin từ tệp tin .pac"
oat_text_10="Chỉ chọn các APK đã được chỉnh sửa có chứa classes*.dex"
name_text="Hợp nhất phân vùng"
default_text="Mặc định"
delete_text="Xoá tệp tin gốc sau khi hoàn thành"
merge_partition_1="Định dạng lưu file"
merge_partition_3="Chọn system để các phân vùng khác gộp vào"
merge_partition_5="Chọn các phân vùng để gộp vào system"
pack_img_text="Không đóng gói"
merge_partition_4="Hợp nhất xong"
merge_partition_text="Hợp nhất các phân vùng khác vào system"
fi
