name: Add-on CI

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/addon/**'

permissions: write-all

jobs:
  build-release:
    if: ${{ github.repository_owner == 'Zenlua' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build add-on
        run: |
          for vv in .github/addon/*; do
          if [ -d "$vv" ]; then
          cd "$vv"
          7z a -t7z -y ../${vv##*/}.add
          cd ~
          fi
          done

      - name: Upload module
        uses: softprops/action-gh-release@v2
        with:
          name: "Tmp"
          tag_name: "V1"
          files: .github/addon/*.add