name: Unpack
on:
  workflow_dispatch:
concurrency:
  group: repo-only
  cancel-in-progress: false
permissions: write-all
env:
    GH_TOKEN: ${{ github.token }}
jobs:
  build:
    name: 'Update File'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Editor File
        run: |
            #mkdir -p WakeLockApp
            rm -fr app
            unzip -o WakeLockApp.zip -d ../
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto delete file" || echo "Nothing to commit"
          git push
