name: PIF
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '.github/Run.sh'
  workflow_dispatch: 
   inputs:
      LIT:
        description: 'Thêm spoof'
        required: false
        default: ''
      LUN:
        description: 'Thêm shell'
        required: false
        default: ''
permissions: write-all
jobs:
  build:
    name: 'See progress'
    if: github.repository == 'Zenlua/Tool-Tree' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      LIT: ${{ inputs.LIT }}
      LUN: ${{ inputs.LUN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Start process'
        run: |
          # Kakathic         
          bash .github/Run.sh
      - name: Upload Pif
        uses: softprops/action-gh-release@v2
        with:
          name: Pif
          tag_name: V1
          files: PIF.json
